config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'homes#top'
  get 'books' => 'books#index'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id)
      flash[:alert] = "Book was successfully created."
    else
      @books = Book.all
      render action: :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:alert] = "Book was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
    flash[:alert] = "Book was successfully destroyed."
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Body</h4>
<%= f.text_area :body %>
<%= f.submit 'Update Book' %>
<%= link_to 'Show', book_path(@book.id) %>
<%= link_to 'Back', books_path %>
<% end %>

app/views/books/index.html.erb
<%= flash[:alert] %>
<h1>Books</h1>
<% @books.each do |book| %>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <tr align="center">
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show", book_path(book.id) %></td>
        <td><%= link_to "Edit", edit_book_path(book.id) %></td>
        <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
      </tr>
    </tbody>
  </table>
<% end %>

<h2>New book</h2>
<%= form_with model:@book, url:'/books', local:true do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<h2>New book</h2>
<%= form_with model: @book, url:'/books', local:true do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <%= f.text_area :body %>
  <%= f.submit 'create book' %>
<% end %>

app/views/books/show.html.erb
<%= flash[:alert] %>
<h2>title</h2>
<p><%= @book.title %></p>
<h2>本文</h2>
<p><%= @book.body %></p>
<%= link_to 'Edit', edit_book_path %>
<%= link_to 'Back', books_path %>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" media="all" href="/assets/application-d12397cbc3a266ce5a99f7b588223090c55ca04a439953bb5f9304395de93fc3.css" data-turbolinks-track="reload">
    <script src="/assets/application-4e370d3723b6f204426a9414077d365ea07814cce5619ae24fb7e581988f19ed.js" data-turbolinks-track="reload"></script>
    <title>WebCampBackendNew</title>
    <meta name="csrf-param" content="authenticity_token">
    <meta name="csrf-token" content="Iddu/kHZOmec67hn4E1aSLrWpDo8Iq4vGyhgOOZXpMcjhxwIF0YL5/nyQR+v6U4jGnsMi5z5226y/V2cUcq68A==">
  </head>

  <body>
    <h1>
      ようこそ
      <strong>Bookers</strong>
      へ!
    </h1>
    <p>
      <strong>Bookers</strong>
      では、さまざまな書籍に関するあなたの意見や
    </p>
    <p>印象を共有し交換することができます</p>
    <p><a href="/books">start</a></p>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>